### ISSUE TITLE
Implement EndpointInterface for local xml file

### ISSUE THREAD

**Issue by woutgg** [caseyamcl/phpoaipmh#41]
In order to test and experiment with data served by an endpoint, it would be practical if a file from the local filesystem could be used as if its contents were retrieved from a server.

This can come in handy, for instance, when testing how to handle CRUD operations on the source data, for unit testing, or when working on code without internet available.

Writing an additional implementation of the EndpointInterface might be a clean way to do this.

**Comment by caseyamcl** [comment]
I agree. I'm going to set this as a target task for the next version, which will include decoupling some of the tightly-coupled components into single-responsibility classes.

**Comment by caseyamcl** [comment]
Hi @woutgg, I know this issue has been hanging out here for a while, but I made a little bit of progress on it  with the [2.6 release](https://github.com/caseyamcl/phpoaipmh/releases/tag/v2.6).

The method signatures now use interfaces instead of concrete class instances.  So, you can implement your own `EndpointInterface`, `ClientInterface`, and `RecordIteratorInterface` if you wish.  You'll have to code these yourself, but they will integrate with existing classes now.

In the 3.0 release, I anticipate further decoupling to make customization like this easier.

**Comment by caseyamcl** [comment]
Hi @woutgg, just FYI, since this is an edge-case, I don't think I'm going to implement explicit local file support (yet). 

However, if you are using Guzzle v6, you can use the `MockHandler` to return local files  (there is also a way to do it in v5, but you'll have to look at the docs):

```
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use Phpoaipmh\Endpoint;
use Phpoaipmh\Client;
use Phpoaipmh\HttpAdapter\GuzzleAdapter;

// Iterate over a bunch of files, one at a time
$mock = new MockHandler([
    new Response(200, [], fopen('/path/to/file1.xml'),
    new Response(200, [], fopen('/path/to/file2.xml'),
    new Response(200, [], fopen('/path/to/file3.xml'),
    // etc.... 
]);

$handler = HandlerStack::create($mock);
$endpoint = new Endpoint(new Client('/', new GuzzleAdapter(new GuzzleClient(['handler' => $handler]))));

// etc...
```

There are even more tricks you can do by creating your own [Guzzle handler](http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#handlers), but I'll leave those up to you.

Another option is to simply create your own instance of `Phpoaipmh\HttpAdapter\HttpAdapterInterface` or `Phpoaimph\ClientInterface`.  If you do that, and think that your code is generally useful, I encourage you to submit a PR.
