### ISSUE TITLE
Error using oai_dc

### ISSUE THREAD

**Issue by trmurakami** [caseyamcl/phpoaipmh#42]
Hi, 

If I use oai_dc in metadata format, metadata field returns empty. If I use others formats, this field return filled. This is a error?

**Comment by caseyamcl** [comment]
Hm.  Let me see if I can recreate this problem and have a look.  Is the endpoint that you're connecting to public or private?  If it is a public endpoint, do you mind sharing the URL?

**Comment by trmurakami** [comment]
This is an example: http://revistas.ufpr.br/atoz/oai. But in my instalation, I cannot harvest any DC in Open Journal System software.

**Comment by caseyamcl** [comment]
Hi @trmurakami ... Okay, I looked into this, and it is not an error.  The endpoint is returning all of the data.  You can confirm this by doing the following:

```php
$iterator = $endpoint->listRecords('oai_dc');
$item = $iterator->current();
var_dump($item->asXML());
```

..and you'll see all of the data.

The issue you're running into is XML namespaces, which are kind of a pain.  Refer to the code below:

```php
$iterator = $endpoint->listRecords('oai_dc');
$item = $iterator->current();

// This works:
echo "\n" . $item->header->identifier();

// This doesn't work:
echo "\n" . $item->metadata->dc->title;
```

The reason the second `echo` statement doesn't work, is because the tags are namespaced.  You either have to strip the namespaces from XML or import them in order to access the values:

```php
$iterator = $endpoint->listRecords('oai_dc');

foreach ($iterator as $item) {

   $data = $item->metadata->children( 'http://www.openarchives.org/OAI/2.0/oai_dc/' );
   $rows = $data->children( 'http://purl.org/dc/elements/1.1/' );
   echo $rows->title;
}
```

Further reading: https://www.sitepoint.com/simplexml-and-namespaces/

**Comment by trmurakami** [comment]
Thanks!!!
